# ╭──────────────────────────────────────────────────────────────────╮
# │ NOTE: This is a reference implementation for educational purposes │
# │ Please test thoroughly before applying to production environments │
# ╰──────────────────────────────────────────────────────────────────╯

# pod-without-auto-mount.yaml
# Pod configuration that disables automatic token mounting
apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  automountServiceAccountToken: false
  containers:
  - name: app
    image: app:latest
---
# dedicated-service-account.yaml
# Create a dedicated service account with minimal permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-specific-sa
  namespace: application
---
# minimal-role-binding.yaml
# Bind minimal permissions to the dedicated service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-specific-binding
  namespace: application
subjects:
- kind: ServiceAccount
  name: app-specific-sa
  namespace: application
roleRef:
  kind: Role
  name: app-minimal-role
  apiGroup: rbac.authorization.k8s.io
---
# app-minimal-role.yaml
# Minimal permissions role for the application
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-minimal-role
  namespace: application
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["app-config"]
  verbs: ["get"]
---
# disable-default-sa.yaml
# Patch the default service account to disable token auto-mounting
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: application
automountServiceAccountToken: false
